apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wmqsk50e4-go 
  janus-idp.io/tekton: wmqsk50e4-go
  backstage.io/kubernetes-id: wmqsk50e4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wmqsk50e4-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml